/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Scan */
        post: operations["preview_scan_api_scans_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Finding */
        Finding: {
            /** Id */
            id: string;
            /** Agent */
            agent: string;
            /** Category */
            category: string;
            severity: components["schemas"]["Severity"];
            /** File Path */
            file_path: string;
            /** Line */
            line?: number | null;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Snippet */
            snippet?: string | null;
            /** Regulations */
            regulations?: components["schemas"]["RegulationRef"][];
            /** Recommendation */
            recommendation: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RegulationRef */
        RegulationRef: {
            /**
             * Framework
             * @enum {string}
             */
            framework: "GDPR" | "APP";
            /** Clause */
            clause: string;
            /** Summary */
            summary: string;
        };
        /** ScanRequest */
        ScanRequest: {
            /** Repo Path */
            repo_path: string;
        };
        /** ScanSummary */
        ScanSummary: {
            /** Score */
            score: number;
            /** Total Findings */
            total_findings: number;
            /** Counts By Severity */
            counts_by_severity: {
                [key: string]: number;
            };
            /** Findings */
            findings: components["schemas"]["Finding"][];
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "critical" | "high" | "medium" | "low";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    preview_scan_api_scans_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
