/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Scan */
        post: operations["preview_scan_api_scans_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixes/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Fixes */
        post: operations["generate_fixes_api_fixes_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/fixes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Scan Fixes */
        post: operations["generate_scan_fixes_api_scans_fixes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentFailure */
        AgentFailure: {
            /** Agent */
            agent: string;
            /** Message */
            message: string;
        };
        /** Finding */
        Finding: {
            /** Id */
            id: string;
            /** Violation Type */
            violation_type: string;
            /** Agent */
            agent: string;
            /** Category */
            category: string;
            severity: components["schemas"]["Severity"];
            /** File Path */
            file_path: string;
            /** Line */
            line?: number | null;
            /** Context */
            context?: string | null;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Snippet */
            snippet?: string | null;
            /** Regulations */
            regulations?: components["schemas"]["RegulationRef"][];
            /** Regulation Warning */
            regulation_warning?: string | null;
            /** Recommendation */
            recommendation: string;
            /** Remediation Hint */
            remediation_hint: string;
        };
        /** FixFailure */
        FixFailure: {
            /** Finding Id */
            finding_id?: string | null;
            /** File Path */
            file_path?: string | null;
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * FixOutputType
         * @enum {string}
         */
        FixOutputType: "local_diff" | "github_pr";
        /** FixPatch */
        FixPatch: {
            /** Finding Id */
            finding_id: string;
            /** File Path */
            file_path: string;
            /** Diff */
            diff: string;
            /** Patch Path */
            patch_path?: string | null;
            /**
             * Applied
             * @default false
             */
            applied: boolean;
        };
        /** FixRequest */
        FixRequest: {
            /** Repo Path */
            repo_path: string;
            /** Findings */
            findings?: components["schemas"]["Finding"][];
            finding?: components["schemas"]["Finding"] | null;
            /**
             * Apply
             * @default false
             */
            apply: boolean;
            /**
             * Create Pr
             * @default false
             */
            create_pr: boolean;
            /**
             * Rescan
             * @default false
             */
            rescan: boolean;
            /** Patch Dir */
            patch_dir?: string | null;
        };
        /** FixSummary */
        FixSummary: {
            output_type: components["schemas"]["FixOutputType"];
            /** Pr Url */
            pr_url?: string | null;
            /** Patch Path */
            patch_path?: string | null;
            /** Diff */
            diff: string;
            /** Patches */
            patches: components["schemas"]["FixPatch"][];
            /** Failures */
            failures?: components["schemas"]["FixFailure"][];
            /**
             * Applied
             * @default false
             */
            applied: boolean;
            rescan_summary?: components["schemas"]["ScanSummary"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RegulationRef */
        RegulationRef: {
            /**
             * Framework
             * @enum {string}
             */
            framework: "GDPR" | "APP";
            /** Clause */
            clause: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Requirement */
            requirement: string;
            /** Max Penalty */
            max_penalty: string;
            severity: components["schemas"]["Severity"];
        };
        /** ScanRequest */
        ScanRequest: {
            /** Repo Path */
            repo_path: string;
        };
        /**
         * ScanStatus
         * @enum {string}
         */
        ScanStatus: "complete" | "partial" | "failed";
        /** ScanSummary */
        ScanSummary: {
            scan_status: components["schemas"]["ScanStatus"];
            /** Score */
            score: number;
            /** Total Findings */
            total_findings: number;
            /** Counts By Severity */
            counts_by_severity: {
                [key: string]: number;
            };
            /** Counts By Agent */
            counts_by_agent: {
                [key: string]: number;
            };
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /** Failed Agents */
            failed_agents: components["schemas"]["AgentFailure"][];
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "critical" | "high" | "medium" | "low";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    preview_scan_api_scans_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_fixes_api_fixes_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FixRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_scan_fixes_api_scans_fixes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FixRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
